apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "metabase.fullname" . }}-log4j2
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
data:
    log4j2.xml: |-
        <?xml version="1.0" encoding="UTF-8"?>
        <Configuration>
        <Appenders>
            <Console name="STDOUT" target="SYSTEM_OUT" follow="true">
            <PatternLayout pattern="%style{%date}{white} | %highlight{%level}{ERROR=bright red, WARN=bright yellow, INFO=bright green, DEBUG=bright cyan} | %logger | %message%n%throwable">
                <replace regex=":basic-auth \\[.*\\]" replacement=":basic-auth [redacted]"/>
            </PatternLayout>
            <Filters>
                <RegexFilter regex=".*\/api\/health.*" onMatch="DENY" onMismatch="NEUTRAL"/>
            </Filters>
            </Console>
        </Appenders>

        <Loggers>
            <Logger name="metabase" level="INFO"/>
            <Logger name="metabase.sync" level="ERROR"/>
            <Logger name="metabase.driver" level="ERROR"/>
            <Logger name="metabase.server.middleware" level="DEBUG"/>

            <Root level="ERROR">
            <AppenderRef ref="STDOUT"/>
            </Root>
        </Loggers>
        </Configuration>
