# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
nameOverride: ""
fullnameOverride: ""
global:
  secrets:
    databasePassword: ~
    databaseName: 'metabase'
    databaseUser: 'metabase'
    annotation:
      helm.sh/policy: "keep"
  zone: 'prod' # it is required, could be pr-123, dev, test, prod
  domain: "apps.silver.devops.gov.bc.ca" # it is required, apps.silver.devops.gov.bc.ca for silver cluster

metabase:
  enabled: true
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  deploymentStrategy: Recreate
  image:
    repository: ghcr.io/bcgov/nr-metabase/metabase
    pullPolicy: Always
  # the below is for renovate to keep pushing PRs, so that it keeps getting updated.
  metabaseImage:
    repository: metabase/metabase
    tag: v0.52.5
  containerPort: 3000
  environment: production
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
  autoscaling:
    enabled: false
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  nodeSelector: {}
  tolerations: []
  affinity: {}
database:
  enabled: true
  replicaCount: 1
  nameOverride: ""
  fullnameOverride: ""
  deploymentStrategy: Recreate
  image:
    repository: ghcr.io/bcgov/nr-containers/postgres
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: '15.10'
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  imagePullSecrets: []
  autoscaling:
    enabled: false
  service:
    type: ClusterIP
    port: 5432
    targetPort: 5432
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    requests:
      cpu: 150m
      memory: 500Mi
  persistence:
    enabled: true
    size: 512Mi
    accessMode: ReadWriteMany
    storageClass: netapp-file-standard
backup:
  enabled: true
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: bcgovimages/backup-container
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: latest
  persistence:
    accessModes:
      - ReadWriteOnce
    mountPath: "/backups/"
    size: 256Mi #Volume space available for data, e.g. 512Mi, 2Gi.
    storageClass: "netapp-block-standard"
  schedule: "0 0 * * *" # cron job schedule
  strategy: "rolling" # daily or rolling
  numBackups: 5 # The number of backup files to be retained.  Used for the `daily` backup strategy.  Ignored when using the `rolling` backup strategy.
  dailyBackups: 7 # The number of daily backup files to be retained.  Used for the `rolling` backup strategy.
  weeklyBackups: 4 # The number of weekly backup files to be retained.  Used for the `rolling` backup strategy.
  monthlyBackups: 1 # The number of monthly backup files to be retained.  Used for the `rolling` backup strategy.
  serviceAccount: default # "Name of the Service Account To Execute the Job As."
  successHistoryLimit: 5 # "The number of successful jobs that will be retained"
  failedHistoryLimit: 2 # "The number of failed jobs that will be retained"
  backoffLimit: 0 # "The number of attempts to try for a successful job outcome"
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
