apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "metabase.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "metabase.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "metabase.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "image-registry.openshift-image-registry.svc:5000/{{.Release.Namespace}}/{{ include "metabase.fullname" . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MB_DB_DBNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.global.zone }}
                  key: databaseName
            - name: MB_DB_PORT
              value: "5432"
            - name: MB_DB_HOST
              value: {{ .Release.Name }}-database-{{ .Values.global.zone }}
            - name: MB_DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.global.zone }}
                  key: databaseUser
            - name: MB_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.global.zone }}
                  key: databasePassword
            - name: MB_DB_TYPE
              value: postgres
            - name: TZ
              value: America/Vancouver
            - name: MB_ENCRYPTION_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-{{ .Values.global.zone }}
                  key: databasePassword
            - name: DB_PORT
              value: "5432"
            - name: MB_JETTY_HOST
              value: 0.0.0.0
            - name: MB_PASSWORD_COMPLEXITY
              value: strong
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Values.global.zone }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 50
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
