---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "metabase.fullname" . }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: "{{ .Values.global.appVersion }}"
      from:
        kind: DockerImage
        name: "{{ .Values.image.repository }}:{{ .Values.global.appVersion }}"
      referencePolicy:
        type: Local
