kind: CronJob
apiVersion: "batch/v1"
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
spec:
  schedule: {{.Values.schedule | quote}}
  concurrencyPolicy: "Replace"
  successfulJobsHistoryLimit: {{.Values.successHistoryLimit }}
  failedJobsHistoryLimit: {{.Values.failedHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "backup.labels" . | nindent 8 }}
    spec:
      backoffLimit: {{.Values.backoffLimit}}
      template:
        metadata:
          labels:
            {{- include "backup.labels" . | nindent 12 }}
        spec:
          containers:
            - name: {{ include "backup.fullname" . }}
              image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
              command:
                - "/bin/bash"
                - "-c"
                - "/backup.sh -1"
              volumeMounts:
                - mountPath: {{ .Values.persistence.mountPath }}
                  name: "backup"
              env:
                - name: BACKUP_DIR
                  value: {{ .Values.persistence.mountPath | quote }}
                - name: BACKUP_STRATEGY
                  value: {{ .Values.strategy | quote }}
                - name: NUM_BACKUPS
                  value: {{ .Values.numBackups | quote }}
                - name: DAILY_BACKUPS
                  value: {{ .Values.dailyBackups | quote }}
                - name: WEEKLY_BACKUPS
                  value: {{ .Values.weeklyBackups | quote }}
                - name: MONTHLY_BACKUPS
                  value: {{ .Values.monthlyBackups | quote }}
                - name: DATABASE_SERVICE_NAME
                  value: {{.Release.Name}}-database-{{.Values.global.zone}}
                - name: DEFAULT_PORT
                  value: "5432"
                - name: POSTGRESQL_DATABASE
                  value: "fin-pay-transparency"
                - name: DATABASE_USER
                  valueFrom:
                    secretKeyRef:
                      name: {{.Release.Name}}-{{.Values.global.zone}}
                      key: "databaseUser"
                - name: DATABASE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{.Release.Name}}-{{.Values.global.zone}}
                      key: "databasePassword"
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: {{ include "backup.fullname" . }}
          restartPolicy: "Never"
          terminationGracePeriodSeconds: 30
          activeDeadlineSeconds: 1600
          dnsPolicy: "ClusterFirst"
          serviceAccountName: {{ .Values.serviceAccount }}
