---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.global.zone }}
  labels: {{- include "selectorLabels" . | nindent 4 }}
data:
  databasePassword: {{ .Values.global.secrets.databasePassword | b64enc | quote }}
  databaseUser: {{  .Values.global.secrets.databaseUser | b64enc | quote }}
  databaseName: {{  .Values.global.secrets.databaseName | b64enc | quote }}
