name: semantic release

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions: {}

jobs:
  vars:
    name: Set Variables
    permissions:
      packages: write
    runs-on: ubuntu-24.04
    timeout-minutes: 1
    steps:
      # Get PR number for squash merges to main
      - name: PR Number
        id: pr
        uses: bcgov/action-get-pr@21f9351425cd55a98e869ee28919a512aa30647d # v0.0.1

      - name: Metabase Version
        id: metabase_version
        run: |
          appVersion=$(yq '.metabase.metabaseImage.tag' charts/nr-metabase/values.yaml)
          echo "app version is $appVersion"
          echo "app_version=$appVersion" >> "$GITHUB_OUTPUT"
      - uses: shrink/actions-docker-registry-tag@f04afd0559f66b288586792eb150f45136a927fa # v4
        with:
          registry: ghcr.io
          repository: ${{ github.repository }}/metabase
          target: ${{ steps.pr.outputs.pr }}
          tags: |
            ${{ steps.metabase_version.outputs.app_version }}

  helm-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: package helm chart
        shell: bash
        run: |
          APP_VERSION=$(yq '.metabase.metabaseImage.tag' charts/nr-metabase/values.yaml)
          # remove v from version as it only needs the numbers without v
          VERSION=$(echo $APP_VERSION | sed 's/v//')
          helm package -u --destination=.cr-release-packages --app-version="$APP_VERSION" --version=$VERSION charts/${{ github.event.repository.name }}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          skip_packaging: 'true'


